local background = Instance.new('ScrollingFrame')
background.Size = UDim2.new(1, 0, 1, 0)
background.AnchorPoint = Vector2.new(0, 0)
background.Position = UDim2.new(0, 0, 0, 0)
background.BackgroundColor3 = Color3.new(0, 0, 0)
background.BorderSizePixel = 0
background.Visible = true
background.ScrollBarThickness = 2
background.ScrollBarImageColor3 = Color3.new(1, 1, 1)
background.ScrollBarImageTransparency = 0
return background
