return {
	toggleEnabled = 'rbxasset://textures/CollisionGroupsEditor/checked-bluebg.png',
	toggleDown = 'rbxasset://textures/CollisionGroupsEditor/checked-whitebg.png',
	toggleDisabled = 'rbxasset://textures/CollisionGroupsEditor/unchecked.png',
	topScroll = 'rbxasset://textures/ui/Scroll/scroll-top.png',
	midScroll = 'rbxasset://textures/ui/Scroll/scroll-middle.png',
	botScroll = 'rbxasset://textures/ui/Scroll/scroll-bottom.png',
}
